versions: "3.8"
services:

  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "app"
      DB_MYSQL_PASSWORD: "app"
      DB_MYSQL_NAME: "app"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./npm/data:/data:Z
      - ./npm/letsencrypt:/etc/letsencrypt:Z

  db:
    image: 'docker.io/jc21/mariadb-aria:latest'
    restart: unless-stopped
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 'app'
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'app'
    volumes:
      - ./npm/mysql:/var/lib/mysql:Z

  homepage:
    image: homepage:1.0
    build: ./personalwebsite
    restart: unless-stopped
    ports:
      - '3002:3002'
    volumes:
      - ./personalwebsite:/app:Z
      - /app/node_modules

  face-web:
    image: face-web:1.1
    build: ./faceapp/face-web
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./faceapp/face-web:/app:Z
      - /app/node_modules

  face-api:
    image: face-api:1.1
    build: ./faceapp/face-api
    restart: unless-stopped
    ports:
      - '3001:3001'
    volumes:
      - ./faceapp/face-api:/app:Z
      - /app/node_modules

  face-db:
    image: face-db:1.0
    privileged: true
    build: ./faceapp/face-db
    # image: postgres:14.8-alpine3.18
    restart: always
    ports:
      - '5432:5432'
    volumes:
    # here we create and link persistant postgres database, so if image is deleted the data is not lost
      - face-db:/var/lib/postgresql/data:Z
    # here we create our initial 'login' and 'user' tables
      # - ./faceapp/face-db/face.sql:/docker-entrypoint-initdb.d/create_tables.sql

  store-web:
    image: store-web:1.1
    build: ./storeapp/store-web
    restart: on-failure
    ports:
      - '4000:4000'
    volumes:
      - ./storeapp/store-web:/app:Z
      - /app/node_modules

  store-api:
    image: store-api:1.0
    build: ./storeapp/store-api
    restart: on-failure
    ports:
      - '4001:4001'
    volumes:
      - ./storeapp/store-api:/app:Z
      - /app/node_modules

  store-db:
    image: store-db:1.0
    privileged: true
    build: ./storeapp/store-db
    restart: always
    ports:
      - '5433:5432'
    volumes:
    # here we create and link persistant postgres database, so if image is deleted the data is not lost
      - store-db:/var/lib/postgresql/data:Z
    # here we create our initial tables
      # - ./storeapp/store-db/store.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  store-db:
    driver: local
  face-db:
    driver: local
