FROM node:20.3.0-alpine3.18

RUN addgroup app && adduser -G app -S app
RUN mkdir /app && chown app:app /app
USER app

WORKDIR /app
COPY --chown=app:app package*.json .
COPY --chown=app:app yarn.lock .
RUN yarn install

COPY --chown=app:app . .

ENV PORT=4001
EXPOSE 4001

CMD ["yarn", "start"]