# FROM node:20.3.0-alpine3.18

# RUN addgroup app && adduser -G app -S app
# RUN mkdir /app && chown app:app /app
# USER app

# WORKDIR /app
# COPY --chown=app:app package*.json .
# RUN npm ci --production

# ENV PORT=3000 
# ENV REACT_APP_API_CALL=http://192.168.50.56:3001
# COPY --chown=app:app . .


# EXPOSE 3000

# CMD ["npm", "start"]


FROM node:20.3.0-alpine3.18

RUN addgroup app && adduser -G app -S app
RUN mkdir /app && chown app:app /app
USER app

WORKDIR /app
COPY --chown=app:app package.json .
COPY --chown=app:app yarn.lock .
RUN yarn install
COPY --chown=app:app . .

ENV PORT=3000
ENV REACT_APP_API_CALL=http://face.abdil.ca/api
# ENV NODE_OPTIONS=--openssl-legacy-provider

EXPOSE 3000
RUN yarn run build
RUN yarn global add serve

CMD ["yarn", "run", "server"]