FROM node:20.3.0-alpine3.18

RUN addgroup app && adduser -G app -S app
RUN mkdir /app && chown app:app /app
USER app

WORKDIR /app
COPY --chown=app:app package*.json .
RUN npm install
COPY --chown=app:app . .

# ENV API_CLARIFAI="5dc3929cc3234e2e8ad6117dd0af96c3"
# ENV PORT=3001
# ENV DATABASE_URL=http://localhost:5432

EXPOSE 3001

CMD ["npm", "start"]