# FROM node:20.3.0-alpine3.18

# RUN addgroup app && adduser -G app -S app
# RUN mkdir /app && chown app:app /app
# USER app

# WORKDIR /app
# COPY --chown=app:app package*.json .
# RUN npm install

# ENV PORT=3001
# ENV DATABASE_URL=http://192.168.50.56:5432
# ENV API_CLARIFAI=5dc3929cc3234e2e8ad6117dd0af96c3

# COPY --chown=app:app . .

# EXPOSE 3001

# CMD ["npm", "start"]


FROM node:20.3.0-alpine3.18

RUN addgroup app && adduser -G app -S app
RUN mkdir /app && chown app:app /app
USER app

WORKDIR /app
COPY --chown=app:app package.json .
COPY --chown=app:app yarn.lock .
RUN yarn install

COPY --chown=app:app . .

ENV PORT=3001
ENV API_CLARIFAI=5dc3929cc3234e2e8ad6117dd0af96c3
EXPOSE 3001

CMD ["yarn", "start"]